# Generated by Django 4.1.4 on 2023-02-13 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('pic', models.ImageField(default='/images/generic/no_pic.jpeg', upload_to=users.models.profile_pic_path)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='groups.group')),
                ('latest_posts_query', models.ManyToManyField(blank=True, related_name='latest_posts_query', to='feed.post')),
                ('requested_friends', models.ManyToManyField(blank=True, related_name='requested_friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
