# Generated by Django 4.1.3 on 2023-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_post_last_edited_at'),
        ('users', '0002_remove_profile_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latest_posts_query',
            field=models.ManyToManyField(blank=True, related_name='latest_posts_query', to='feed.post'),
        ),
    ]
