# Generated by Django 4.1.3 on 2022-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_delete_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/media/images/no_pic.jpeg', upload_to='images/pics/'),
        ),
    ]
