# Generated by Django 4.1.3 on 2022-12-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
