# Generated by Django 4.1.3 on 2023-01-16 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_profile_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_friends',
            field=models.ManyToManyField(related_name='requested_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
