# Generated by Django 4.1.3 on 2022-12-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_alter_postmodel_img'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('postmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.postmodel')),
                ('of_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='groups.group')),
            ],
            bases=('feed.postmodel',),
        ),
    ]
