# Generated by Django 4.1.3 on 2023-02-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
