# Generated by Django 4.1.3 on 2023-02-08 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_rename_created_at_group_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='requested_members',
            field=models.ManyToManyField(blank=True, related_name='requestes_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
