# Generated by Django 4.1.4 on 2023-02-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notifications_channel',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_channel',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
