# Generated by Django 4.1.3 on 2023-01-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notifications_channel',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_channel',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
