# Generated by Django 4.1.3 on 2023-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_client_notifications_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
