# Generated by Django 4.1.3 on 2023-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_client_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notifications_channel',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_channel',
            field=models.CharField(default='', max_length=150),
        ),
    ]
